<template>
  <div
    class="
      md:justify-start md:space-x-10
      flex
      items-center
      justify-center
      my-1
      h-14
      border-b
      border-gray-400
      text-4xl
      font-bold
      text-transparent
      bg-clip-text
      bg-gradient-to-r
      from-blue-500
      to-purple-800
      content-center
    "
  >
    <div>PistonVideo</div>
  </div>
</template>
